### ISSUE TITLE
Not working in IE9

### ISSUE THREAD

**Issue by RobDaubin** [tardate/jquery.addtocalendar#9]
I have it working in FF, Chrome, Safari and IE8.  Will not work in IE9 and I can't determine why.  When i rollover the main link in any of the working browsers, the cursor turns into a hand pointer an, when clicked, I get the dropdown menu.  In IE9, the cursor turns into a text editor and nothing happens when I click.  Any ideas?

thanks.

**Comment by avantix** [comment]
There is an extra comma in the Widget Initalization code.

When it says:

```
   url: null
    };
},
```

  });

It should be

```
   url: null
    };
}
```

  });

I've done this and now it works in IE9, FF and Chrome, haven't tested in Safari yet.

I still have an issue in IE9 with the calendar menu's width, but I don't know if it's because of my HTML.

**Comment by tardate** [comment]
Thanks for checking this out @avantix - I don't have an IE9 to hand at the moment.

This is just a "documentation bug" isn't it? i.e. you are referring to the example in the README I think. We had most IE fixes included in v0.1.1 thanks to @nfarina

**Comment by avantix** [comment]
Yes, for me it was just a "documentation bug".

**Comment by tardate** [comment]
ta!

@robinsf I'll close this issue then - but tell us if you are still having other problems
